<!DOCTYPE html>

<!--[if lt IE 7 ]> <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js"> <!--<![endif]-->

<head>
<?php echo $this->getChildHtml('head') ?>
</head>

<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
    <?php echo $this->getChildHtml('navside') ?>
    <div class="page">
        <?php echo $this->getChildHtml('header') ?>
        <div class="scroll-wrapper">
            <div class="main-container col1-layout">
                <div class="main">
                    <?php echo $this->getChildHtml('breadcrumbs') ?>
                    <div class="col-main">
                        <?php echo $this->getChildHtml('global_messages') ?>
                        <?php echo $this->getChildHtml('content') ?>
                    </div>
                </div>
            </div>
            <?php echo $this->getChildHtml('footer_before') ?>
            <?php echo $this->getChildHtml('footer') ?>
        </div>
        <?php echo $this->getChildHtml('global_cookie_notice') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
        <div id="page-overlay"></div>
        <div class="modal-confirm modal-logout">
            <div class="modal-container">
                <h2 class="modal-title"><?php echo $this->__('Sign out of My Account?') ?></h2>
                <div class="modal-body"></div>
                <div class="modal-buttons clearfix">
                    <div class="btn-set fl">
                        <a href="#" class="btn btn-cancel"><?php echo $this->__('No') ?></a>
                    </div>
                    <div class="btn-set fr">
                        <a href="<?php echo Mage::helper('customer')->getLogoutUrl(); ?>" class="btn btn-logout"><?php echo $this->__('Yes') ?></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>