<style type="text/css">
	.button {width: 100%;margin: 24px 0;line-height: 40px;font-size: 18px;font-weight: normal;cursor: default;background: #351611;color: #fff;border-radius: 3px;}
	.accept-li {display: inline-block;border: 1px solid #b5b5b5;background-size: 295px 330px;background-image: url(https://www.burberry.com/app/a7f0d0770c52867b55b93136cd055e7f.png);}
	.accept-li-one {background-position: -125px -52px;width: 45px;height: 29px;}
	.accept-li-two {margin-left: 20px;background-position: -68px -52px;width: 45px;height: 29px;}
	.accept-li-three {margin-left: 20px;background-position: -68px -11px;width: 45px;height: 29px;}
</style>


<div style="padding: 60px 20px;text-align: center;">
	<div style="padding: 20px 0;border-bottom: 1px solid #999;">
		<span class="iconfont icon-bag" style="display: block;"></span>
		<span><?php echo $_counts; ?> item</span>
	</div>
	<a href="/my-account/bag" class="">
		<div class="">
			<ul>
				<li class="media-asset ratio ratio3-4 media-asset-image media-asset-loaded">
					<div title="" class="" style="background-image: url(&quot;//assets.burberry.com/is/image/Burberryltd/1ce16215a221e2830bcc7a918922c127964fac58.jpg?$BBY_V2_SL_3X4$&amp;hei=525&amp;wid=394&quot;);"></div>
				</li>
				<li class="">
					<div title="" class="" style="background-image: url(&quot;//assets.burberry.com/is/image/Burberryltd/b331e01aac16b7c02d9e2f9615e5f701bd9284cd.jpg?$BBY_V2_ML_3X4$&amp;hei=525&amp;wid=394&quot;);"></div>
				</li>
			</ul>		
			<span class="iconfont icon-right"></span>		
		</div>
	</a>
	<div class="">
		<dl class="">
			<dt class="">Sub total</dt>
			<dd class=""><?php echo $_prices; ?></dd>		
			<dt class="">Express</dt>
			<dd class="">Free</dd>
		</dl>
		<dl class="">
			<dt class="">
				<strong><span class="">Estimated total</span></strong>
			</dt>
			<dd class=""><strong>$8,690.00</strong></dd>
		</dl>
	</div>
	<div class="">
		<p class="">All orders will be fulfilled by Burberry Limited and shipped from the UK. When you place your order you accept <a href="#" class="">Burberry Ltd’s terms</a> and our <a href="#" class="">privacy policy</a>.&nbsp;</p>
		<div class="button" href="#" title="Order and pay">Order and pay</div>
	</div>
</div>
<div style="margin: 0 20px 50px 20px;text-align: center;">
	<p class="">We accept</p>
	<ul class="">	
		<li class="accept-li accept-li-one"></li>
		<li class="accept-li accept-li-two"></li>
		<li class="accept-li accept-li-three"></li>
	</ul>
	<p class="">Secure shopping</p>
	<span class="iconfont icon-pinterest"></span>
</div>